openapi: 3.0.3
info:
  title: AI 에이전트 및 스킬 시스템 명세 API
  description: AI 에이전트 및 스킬 시스템의 기능 명세를 위한 API 정의
  version: 1.0.0
  contact:
    name: liar-game 개발팀
    email: dev@liar-game.com

servers:
  - url: http://localhost:4000/api/v1
    description: 개발 환경

tags:
  - name: agents
    description: AI 에이전트 시스템 명세
  - name: skills
    description: 자동화 스킬 시스템 명세
  - name: integration
    description: 에이전트-스킬 통합 명세

paths:
  /agents/specification:
    get:
      tags:
        - agents
      summary: 에이전트 시스템 전체 명세 조회
      description: 6개 전문 에이전트의 전체 기능 명세를 반환
      operationId: getAgentsSpecification
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/AgentsSpecification'

  /agents/{agentId}:
    get:
      tags:
        - agents
      summary: 특정 에이전트 명세 조회
      description: 특정 에이전트의 상세 기능 명세를 반환
      operationId: getAgentSpecification
      parameters:
        - name: agentId
          in: path
          required: true
          description: 에이전트 ID
          schema:
            type: string
            enum: [database-architect, auth-security-specialist, game-logic-analyzer, kubernetes-deployment-expert, react-frontend-developer, ui-ux-designer]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/AgentSpecification'
        '404':
          $ref: '#/components/responses/NotFound'

  /skills/specification:
    get:
      tags:
        - skills
      summary: 스킬 시스템 전체 명세 조회
      description: 8개 자동화 스킬의 전체 기능 명세를 반환
      operationId: getSkillsSpecification
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/SkillsSpecification'

  /skills/{skillId}:
    get:
      tags:
        - skills
      summary: 특정 스킬 명세 조회
      description: 특정 스킬의 상세 기능 명세를 반환
      operationId: getSkillSpecification
      parameters:
        - name: skillId
          in: path
          required: true
          description: 스킬 ID
          schema:
            type: string
            enum: [api-endpoint-generator, websocket-gateway-builder, typeorm-migration-generator, docker-k8s-optimizer, nestjs-test-specialist, react-component-generator, supabase-auth-integrator, responsive-page-builder]
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/SkillSpecification'
        '404':
          $ref: '#/components/responses/NotFound'

  /integration/architecture:
    get:
      tags:
        - integration
      summary: 통합 아키텍처 명세 조회
      description: 에이전트-스킬 통합 아키텍처와 협업 메커니즘 명세를 반환
      operationId: getIntegrationArchitecture
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/IntegrationArchitecture'

  /integration/patterns:
    get:
      tags:
        - integration
      summary: 협업 패턴 명세 조회
      description: 에이전트와 스킬의 협업 패턴과 사용 시나리오 명세를 반환
      operationId: getCollaborationPatterns
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/CollaborationPatterns'

components:
  schemas:
    AgentsSpecification:
      type: object
      required:
        - version
        - agents
        - architecture
      properties:
        version:
          type: string
          example: "1.0.0"
        agents:
          type: array
          items:
            $ref: '#/components/schemas/AgentSpecification'
        architecture:
          $ref: '#/components/schemas/AgentArchitecture'
        lastUpdated:
          type: string
          format: date-time

    AgentSpecification:
      type: object
      required:
        - id
        - name
        - expertise
        - capabilities
        - tools
        - outputFormat
      properties:
        id:
          type: string
          example: "database-architect"
          description: 에이전트 고유 식별자
        name:
          type: string
          example: "Database Architect"
          description: 에이전트 명칭
        description:
          type: string
          example: "데이터베이스 아키텍처 및 성능 최적화 전문가"
        expertise:
          $ref: '#/components/schemas/ExpertiseDomain'
        capabilities:
          type: array
          items:
            type: string
          example: ["스키마 설계", "성능 최적화", "쿼리 분석"]
        tools:
          type: array
          items:
            type: string
            enum: [read, glob, grep, write, edit, bash]
        systemPrompt:
          type: string
          description: 에이전트 시스템 프롬프트
        outputFormat:
          $ref: '#/components/schemas/OutputFormat'
        reviewChecklist:
          type: array
          items:
            type: string
          description: 검토 체크리스트 항목
        constitutionCompliance:
          type: array
          items:
            type: string
          description: 준수해야 할 헌법 원칙

    ExpertiseDomain:
      type: string
      enum:
        - database
        - auth-security
        - game-logic
        - kubernetes
        - react-frontend
        - ui-ux-design

    AgentArchitecture:
      type: object
      properties:
        definitionFormat:
          type: string
          enum: [yaml-frontmatter, markdown-header]
          description: 에이전트 정의 파일 형식
        promptStructure:
          type: array
          items:
            type: string
          description: 시스템 프롬프트 구성 요소
        toolAccessPattern:
          type: string
          description: 도구 접근 패턴
        qualityAssurance:
          type: object
          properties:
            reviewProcess:
              type: string
            outputStandards:
              type: array
              items:
                type: string

    OutputFormat:
      type: object
      properties:
        structure:
          type: string
          description: 출력 결과물 구조
        prioritySystem:
          type: string
          enum: [critical, improvement, review]
          description: 우선순위 분류 시스템
        locationFormat:
          type: string
          pattern: "file:line"
          description: 문제점 위치 지정 형식

    SkillsSpecification:
      type: object
      required:
        - version
        - skills
        - architecture
      properties:
        version:
          type: string
          example: "1.0.0"
        skills:
          type: array
          items:
            $ref: '#/components/schemas/SkillSpecification'
        architecture:
          $ref: '#/components/schemas/SkillArchitecture'
        lastUpdated:
          type: string
          format: date-time

    SkillSpecification:
      type: object
      required:
        - id
        - name
        - category
        - inputRequirements
        - outputArtifacts
        - templates
      properties:
        id:
          type: string
          example: "api-endpoint-generator"
        name:
          type: string
          example: "API Endpoint Generator"
        description:
          type: string
          example: "NestJS API 엔드포인트 전체 생성"
        category:
          $ref: '#/components/schemas/SkillCategory'
        inputRequirements:
          type: object
          properties:
            required:
              type: array
              items:
                type: string
            optional:
              type: array
              items:
                type: string
        outputArtifacts:
          type: array
          items:
            $ref: '#/components/schemas/Artifact'
        templates:
          type: array
          items:
            $ref: '#/components/schemas/Template'
        integration:
          $ref: '#/components/schemas/SkillIntegration'
        qualityStandards:
          type: object
          properties:
            codeQuality:
              type: array
              items:
                type: string
            testing:
              type: array
              items:
                type: string
            documentation:
              type: array
              items:
                type: string

    SkillCategory:
      type: string
      enum:
        - api-generation
        - frontend-component
        - database-migration
        - auth-integration
        - infrastructure
        - testing
        - real-time-communication
        - responsive-design

    Artifact:
      type: object
      properties:
        type:
          type: string
          enum: [controller, service, dto, entity, component, test, migration, config, documentation]
        path:
          type: string
          example: "src/auth/auth.controller.ts"
        template:
          type: string
          description: 생성될 파일의 템플릿 내용
        validation:
          type: array
          items:
            type: string
          description: 생성 결과물 검증 규칙

    Template:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        content:
          type: string
        variables:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              type:
                type: string
              required:
                type: boolean
              description:
                type: string

    SkillArchitecture:
      type: object
      properties:
        directoryStructure:
          type: string
          pattern: "[skill-name]/SKILL.md"
        definitionFormat:
          type: object
          properties:
            frontmatter:
              type: object
            content:
              type: string
        codeGenerationPattern:
          type: object
          properties:
            templateEngine:
              type: string
            variableSubstitution:
              type: string
            outputFormatting:
              type: string
        projectIntegration:
          type: object
          properties:
            techStack:
              type: array
              items:
                type: string
            conventions:
              type: array
              items:
                type: string

    SkillIntegration:
      type: object
      properties:
        projectTechStack:
          type: array
          items:
            type: string
          example: ["NestJS 11", "TypeScript", "TypeORM"]
        conventions:
          type: array
          items:
            type: string
          example: ["SOLID principles", "TypeScript types", "Korean comments"]
        dependencies:
          type: array
          items:
            type: string
        testing:
          type: object
          properties:
            framework:
              type: string
            coverage:
              type: string
            patterns:
              type: array
              items:
                type: string

    IntegrationArchitecture:
      type: object
      properties:
        systemOverview:
          type: string
        collaborationModel:
          type: object
          properties:
            agentSelection:
              type: string
            skillExecution:
              type: string
            resultIntegration:
              type: string
        communicationProtocols:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              description:
                type: string
              protocol:
                type: string
        qualityAssurance:
          type: object
          properties:
            validation:
              type: array
              items:
                type: string
            standards:
              type: array
              items:
                type: string
        constitutionCompliance:
          type: object
          properties:
            principles:
              type: array
              items:
                type: string
            enforcement:
              type: array
              items:
                type: string

    CollaborationPatterns:
      type: object
      properties:
        scenarios:
          type: array
          items:
            $ref: '#/components/schemas/CollaborationScenario'
        workflows:
          type: array
          items:
            $ref: '#/components/schemas/Workflow'
        bestPractices:
          type: array
          items:
            type: string
        commonPitfalls:
          type: array
          items:
            type: string

    CollaborationScenario:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        agents:
          type: array
          items:
            type: string
        skills:
          type: array
          items:
            type: string
        steps:
          type: array
          items:
            type: object
            properties:
              action:
                type: string
              agent:
                type: string
              skill:
                type: string
              output:
                type: string
        expectedOutcome:
          type: string

    Workflow:
      type: object
      properties:
        name:
          type: string
        trigger:
          type: string
        steps:
          type: array
          items:
            type: object
            properties:
              step:
                type: integer
              description:
                type: string
              agent:
                type: string
              skill:
                type: string
              input:
                type: object
              output:
                type: string
        successCriteria:
          type: array
          items:
            type: string

  responses:
    NotFound:
      description: 요청한 리소스를 찾을 수 없음
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "NOT_FOUND"
                  message:
                    type: string
                    example: "요청한 에이전트 또는 스킬을 찾을 수 없습니다"
                  details:
                    type: object
                availableOptions:
                  type: array
                  items:
                    type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []