export enum GameStatus {
  WAITING = 'WAITING',
  PLAYING = 'PLAYING',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
}

export enum GamePhase {
  LOBBY = 'LOBBY',
  ASSIGNMENT = 'ASSIGNMENT',
  DISCUSSION = 'DISCUSSION',
  VOTING = 'VOTING',
  RESULT = 'RESULT',
  FINISHED = 'FINISHED',
}